name: CICD

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code to vm
        uses: actions/checkout@v2.3.5
      - name: Install python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.x'
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt    
      - name: Run tests with pytest
        run: pytest